[phases.setup]
nixPkgs = ["nodejs_20", "nginx"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build", "mkdir -p /etc/nginx/conf.d/", "cp nginx.conf /etc/nginx/conf.d/default.conf"]

[start]
cmd = "nginx -g 'daemon off;'"